iceberg_project:
  target: dev
  outputs:
    dev:
      type: trino
      method: none
      host: localhost
      port: 8080
      user: trino
      database: iceberg
      schema: default
      threads: 1