services:
  trino:
    build: .
    container_name: trino
    ports:
      - "8080:8080"
    volumes:
      - warehouse-data:/opt/warehouse
    networks:
      - trino-network
    depends_on:
      - hive-metastore

  hive-metastore:
    image: 'bde2020/hive:2.3.2'
    container_name: hive-metastore
    ports:
      - '9083:9083'
    environment:
      - POSTGRES_URI=jdbc:postgresql://postgres:5432/metastore
      - POSTGRES_USER=hive
      - POSTGRES_PASSWORD=hive
      - POSTGRES_DB=metastore
      - CORE_CONF_fs_defaultFS=file:///
      - CORE_CONF_hadoop_http_staticuser_user=hive
      - HIVE_SITE_CONF_javax_jdo_option_ConnectionURL=jdbc:postgresql://postgres:5432/metastore
      - HIVE_SITE_CONF_javax_jdo_option_ConnectionDriverName=org.postgresql.Driver
      - HIVE_SITE_CONF_javax_jdo_option_ConnectionUserName=hive
      - HIVE_SITE_CONF_javax_jdo_option_ConnectionPassword=hive
      - HIVE_SITE_CONF_datanucleus_autoCreateSchema=true
      - HIVE_SITE_CONF_hive_metastore_uris=thrift://hive-metastore:9083
      - HIVE_SITE_CONF_hive_metastore_schema_verification=false
      - HIVE_SITE_CONF_hive_metastore_warehouse_dir=/opt/warehouse
      - HIVE_SITE_CONF_hive_metastore_event_db_notification_api_auth=false
    volumes:
      - warehouse-data:/opt/warehouse
    networks:
      - trino-network
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:11
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=hive
      - POSTGRES_PASSWORD=hive
      - POSTGRES_DB=metastore
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hive"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - trino-network

volumes:
  warehouse-data:
  postgres-data:

networks:
  trino-network:
    external: true