name: 'iceberg_project'
version: '1.0.0'
config-version: 2

profile: 'iceberg_project'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Configuration specifically optimized for Trino 395
flags:
  require_certificate_validation: False  # Disable SSL certificate validation
  warn_error: False  # Don't treat warnings as errors

query-comment:
  comment: "dbt: {{ env_var('DBT_ENV_NAME', 'dev') }}"
  append: true

# Incremental strategy optimized for Trino 395
models:
  iceberg_project:
    materialized: table
    kafka_to_iceberg:
      materialized: incremental
      +incremental_strategy: append  # Changed from 'merge' to 'append' for better compatibility